"""Weather-forecast consensus filter and observation gate functions.

Extracted from main.py (#6 god-module split): ~1,100 lines of temperature-market
business logic that has nothing to do with polling coordination.

Public API (imported by main.py):
    _ET                         — US Eastern ZoneInfo (also used in adaptive poll)
    _filter_weather_opportunities(opps, markets, ...) → list[NumericOpportunity]
    _apply_forecast_consensus(numeric_opps, data_points, opp_log)
                                → (filtered_opps, obs_value, fc_low_by_metric)

Constants exported for main.py log messages:
    HRRR_MAX_SPREAD_F, TEMP_OBSERVED_MAX_HOURS
"""

import collections
import importlib.util as _ilu
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

from .data import DataPoint
from .numeric_matcher import NumericOpportunity
from .opportunity_log import OpportunityLog
from .utils import env_bool, env_float, env_int, parse_iso_dt
from .cities import CITY_TZ as _CITY_TZ
from .market_parser import ticker_date as _ticker_date
from .scoring import resolve_min_edge as _resolve_min_edge

# ---------------------------------------------------------------------------
# Peak-hour calibration data (moved from main.py module level)
# ---------------------------------------------------------------------------
# Backtest-calibrated per-city p75 peak times (minutes since midnight).
# Generated by scripts/backtest_peak_hour.py — falls back to empty dict if absent.
# p75 = time by which 75% of historical days have seen their daily high.
_PEAK_P75_MINUTES: dict[str, dict[int, int]] = {}
_p90_path = Path(__file__).parent.parent / "data" / "peak_hour_p90.py"
if _p90_path.exists():
    _spec = _ilu.spec_from_file_location("peak_hour_p90", _p90_path)
    if _spec and _spec.loader:
        _p90_mod = _ilu.module_from_spec(_spec)
        _spec.loader.exec_module(_p90_mod)
        _PEAK_P75_MINUTES = getattr(_p90_mod, "P75_MINUTES", {})

_ET = ZoneInfo("America/New_York")

# ---------------------------------------------------------------------------
# Configuration — all overridable via environment variables
# ---------------------------------------------------------------------------

# Gate: suppress noaa_observed / metar YES signals on KXLOWT daily-low markets
# when any forecast model predicts the daily low will be within
# LOWT_FORECAST_GATE_BUFFER_F degrees of (or below) the strike.
# The buffer accounts for NWS day-1 MAE ≈ 3–4°F: a forecast of 54°F with a
# 53°F strike is dangerously close given normal model uncertainty.
# Set NUMERIC_LOWT_FORECAST_GATE=false to disable (not recommended).
NUMERIC_LOWT_FORECAST_GATE: bool = os.environ.get(
    "NUMERIC_LOWT_FORECAST_GATE", "true"
).lower() not in ("false", "0", "no")
LOWT_FORECAST_GATE_BUFFER_F: float = float(
    os.environ.get("LOWT_FORECAST_GATE_BUFFER_F", "3.0")
)
# Minimum independent forecast sources required to agree on YES for KXLOWT
# markets.  Daily lows have ~10% higher MAE than daily highs (overnight lows
# harder to forecast, cold-front timing uncertain).  Requiring 3 sources (vs
# global FORECAST_CORROBORATION_MIN=2) is now achievable since hrrr, nws_hourly,
# and open_meteo all emit temp_low_* DataPoints.
KXLOWT_FORECAST_CORROBORATION_MIN: int = int(
    os.environ.get("KXLOWT_FORECAST_CORROBORATION_MIN", "3")
)
# When noaa_observed/metar fires YES on a KXLOWT market and is NOT suppressed by
# the contradiction gate, require at least this many forecast sources to actively
# confirm the YES direction (fc_low > strike) before allowing the signal through.
# 1 = require one model to agree; 0 = disable (allow if not contradicted).
KXLOWT_OBS_YES_FC_CONFIRM_MIN: int = int(
    os.environ.get("KXLOWT_OBS_YES_FC_CONFIRM_MIN", "1")
)
# Require that at least one of the confirming forecast sources is a near-term
# model (HRRR or NWS hourly) before allowing a KXLOWT observed-YES trade.
# Near-term models have 2–3°F MAE vs 3–5°F for day-ahead global models and
# resolve terrain and cold-front timing that noaa/open_meteo miss overnight.
# Trades #141/#142 (KXLOWTCHI-26APR22-T53): 0 corroborating sources, Chicago
# cold front dropped temp below 53°F after sunrise — near-term gate would
# have blocked both entries. Default: true. Set to false to use any model.
KXLOWT_OBS_YES_NEAR_TERM_REQUIRED: bool = os.environ.get(
    "KXLOWT_OBS_YES_NEAR_TERM_REQUIRED", "true"
).lower() not in ("false", "0", "no")
_KXLOWT_NEAR_TERM_SOURCES: frozenset[str] = frozenset({"hrrr", "nws_hourly"})

# Minimum edge (°F) for observed-temperature YES signals, split by direction:
#
# TEMP_OBSERVED_MIN_EDGE_OVER — direction=over (observed already exceeds strike).
#   We read from the exact same ASOS airport station Kalshi uses for settlement
#   (confirmed from market rules), so station mismatch is ~0°F.  The only risk
#   is NOAA observation lag (typically 30–60 min); 0.5°F covers that comfortably.
#
# TEMP_OBSERVED_MIN_EDGE_BETWEEN — direction=between YES (observed is inside range).
#   Lower bound is confirmed (observed ≥ strike_lo).  Upper bound is only safe
#   AFTER the afternoon gate fires (same 4:30 PM local threshold as under YES).
#   Before 4:30 PM the temperature could still rise above strike_hi, so the gate
#   prevents entry.  After 4:30 PM the day's peak has passed; 0.2°F clearance
#   is sufficient — same logic as direction=over where outcome is locked.
#
# TEMP_OBSERVED_MIN_EDGE_UNDER — direction=under (observed still below strike).
#   The observed max is a lower bound; residual afternoon warming before the
#   4:30 PM gate is the main risk.  2°F provides adequate headroom given lag.
TEMP_OBSERVED_MIN_EDGE_OVER: float = env_float("TEMP_OBSERVED_MIN_EDGE_OVER", 0.5)
TEMP_OBSERVED_MIN_EDGE_BETWEEN: float = env_float("TEMP_OBSERVED_MIN_EDGE_BETWEEN", 0.2)
TEMP_OBSERVED_MIN_EDGE_UNDER: float = env_float("TEMP_OBSERVED_MIN_EDGE_UNDER", 2.0)

# Stricter min edge for noaa_observed/metar between YES on KXLOWT daily-low
# markets.  Unlike KXHIGHT between YES (where the daily peak is confirmed past
# 4:30 PM and the outcome is locked), a KXLOWT between YES entered overnight
# requires the temperature to fall further into the band before settlement.
# The observed running minimum is a ceiling, not the final daily low — cold
# fronts and radiative cooling can push it below the band floor.
# Default 0 = disabled (use TEMP_OBSERVED_MIN_EDGE_BETWEEN for all).
# Will be calibrated from backtest_kxlowt_entry_timing.py results.
KXLOWT_OBS_BETWEEN_YES_MIN_EDGE: float = float(
    os.environ.get("KXLOWT_OBS_BETWEEN_YES_MIN_EDGE", "0.0")
)

# TEMP_OBSERVED_MAX_EDGE — Upper edge cap for noaa_observed signals.
#
# Very large edges (>10°F) on an observed source indicate a faulty reading
# (e.g. sensor error or station reporting a stale value), not a genuine market
# mispricing: a real market rarely prices 10°F+ away from a temperature that has
# already been recorded at settlement.  Post-fix backtest shows all losses on
# noaa_observed were at edges ≥10°F (sensor errors), while all wins were ≤10°F.
# Cap set at 10.0°F; set to a large number to disable.
TEMP_OBSERVED_MAX_EDGE: float = env_float("TEMP_OBSERVED_MAX_EDGE", 10.0)

# TEMP_OBSERVED_MAX_HOURS — For noaa_observed NO signals (observed max is still
#   *below* the strike — the temperature may still rise to hit it), only surface
#   the opportunity within this many hours of market close.  Beyond this window
#   the remaining-day rise is too uncertain.  YES signals (observed max already
#   *exceeds* the strike) are always surfaced — the outcome is locked.
TEMP_OBSERVED_MAX_HOURS: float = env_float("TEMP_OBSERVED_MAX_HOURS", 4.0)

# HRRR_MAX_SPREAD_F — Maximum acceptable spread (°F) between the NWS daily
#   forecast high and the HRRR-derived hourly daytime high.  When the two
#   model products disagree by more than this threshold, the atmosphere is
#   unstable / convectively uncertain and the daily forecast is unreliable.
#   Signals from source="noaa" are suppressed; noaa_observed and
#   nws_alert DataPoints are never gated (they are ground truth / official).
HRRR_MAX_SPREAD_F: float = env_float("HRRR_MAX_SPREAD_F", 8.0)

# MORNING_OBS_GAP_F — Maximum allowed gap (°F) between the Kalshi strike and
#   the current noaa_observed max (recorded since midnight) before a *forecast*
#   YES trade is blocked.  If the observed temperature is more than this many
#   degrees below the strike, a YES forecast is unlikely to be realized even if
#   the model says so — early-morning observations are a reality check.
#   Example: strike=92°F, gap=15°F → observed must be ≥ 77°F to trade YES.
#   Set to 0 to disable (allow any observed gap).
MORNING_OBS_GAP_F: float = env_float("MORNING_OBS_GAP_F", 20.0)

# FORECAST_CORROBORATION_MIN — Minimum number of distinct forecast sources
#   (from {noaa, open_meteo}) that must independently agree on a YES
#   direction before the signal is traded.  Lone signals (only one source)
#   are suppressed — they are more likely to be model noise than genuine alpha.
#   Set to 1 to disable (allow single-source signals).
FORECAST_CORROBORATION_MIN: int = env_int("FORECAST_CORROBORATION_MIN", 2)

# OBS_CONSENSUS_MIN — Minimum number of confirmed-observation sources
#   (noaa_observed, nws_climo) that must independently agree on a YES outcome
#   before the signal is traded.  Set to 1 to allow single-source observation
#   trades; the 4:30 PM peak-past gate on "below threshold" signals provides
#   the primary safety net in place of strict multi-source verification.
#   nws_climo is only available after ~5 PM local, so OBS_CONSENSUS_MIN=2
#   blocked all afternoon observation trades before that window.
OBS_CONSENSUS_MIN: int = env_int("OBS_CONSENSUS_MIN", 1)

# Minimum local hour before a noaa_observed YES trade is allowed.
# Daily temp max is typically established 1–5 PM local; before 1 PM the
# "observed" max is still a morning partial reading — not a confirmed high.
NOAA_OBS_YES_MIN_LOCAL_HOUR: int = env_int("NOAA_OBS_YES_MIN_LOCAL_HOUR", 13)

# Stricter minimum local hour for "below threshold" YES signals (direction=under).
# Observed 66°F against a 76°F strike is only a locked signal AFTER the daily
# temperature peak has passed — at 1 PM there is still 3–4 hours of potential
# warming.  Daily highs are typically established by 4 PM local; requiring
# local hour >= 16 ensures we're already in the cooling-off phase before
# committing to "temp will stay below strike".
NOAA_OBS_PEAK_PAST_LOCAL_HOUR: int = env_int("NOAA_OBS_PEAK_PAST_LOCAL_HOUR", 16)
NOAA_OBS_PEAK_PAST_LOCAL_MINUTE: int = env_int("NOAA_OBS_PEAK_PAST_LOCAL_MINUTE", 30)

# Morning gate for low-temperature observed YES signals (direction=over on
# temp_low_* metrics).  The running daily minimum resets at local midnight and
# at midnight equals the current temperature — not the overnight low, which
# typically occurs at 4–6 AM.  Only allow noaa_observed YES trades on low-temp
# markets after this local hour, by which point the overnight trough has passed
# and the running min is a reliable confirmed floor.
# Default: 05:00 local (typically past the overnight low trough).
# Override via NOAA_OBS_LOW_PAST_LOCAL_HOUR / _MINUTE env vars.
NOAA_OBS_LOW_PAST_LOCAL_HOUR: int = env_int("NOAA_OBS_LOW_PAST_LOCAL_HOUR", 5)
NOAA_OBS_LOW_PAST_LOCAL_MINUTE: int = env_int("NOAA_OBS_LOW_PAST_LOCAL_MINUTE", 0)

# Forecast floor gate for noaa_observed temp_low YES signals.
# After the morning trough, temps rise during the day then drop again at sunset.
# The NWS daily minimum spans the full calendar day — evening cooling can push
# the final daily min below the strike even if the morning min was above it.
# Guard: if tonight's NWS forecast low (source="noaa", day1) is below
# (strike + TEMP_LOW_YES_FORECAST_BUFFER_F), suppress the YES signal.
# Buffer of 0.5°F mirrors NWS integer rounding used in band arb: a forecast
# of 47°F means the official low rounds to 47 (≥46.5) → safe above a 46°F
# strike; a forecast of 46°F could round to 46 = strike → YES won't resolve.
# Set TEMP_LOW_YES_FORECAST_BUFFER_F=0 for strict < strike comparison.
TEMP_LOW_YES_FORECAST_BUFFER_F: float = float(
    os.environ.get("TEMP_LOW_YES_FORECAST_BUFFER_F", "0.5")
)
# If True (default), suppress YES when no tonight forecast is available.
# Set to 'false' to fall back to pre-fix behavior (allow without forecast).
TEMP_LOW_YES_REQUIRE_FORECAST: bool = (
    env_bool("TEMP_LOW_YES_REQUIRE_FORECAST", True)
)
# Only enforce the TEMP_LOW_YES_REQUIRE_FORECAST gate at or after this local
# hour.  Before this hour the signal is about the confirmed overnight/morning
# trough, which is less sensitive to evening cooldown risk.  After this hour
# the temperature is likely still rising (or near peak) and an evening dip
# could invalidate the YES — so the forecast is required.
# Default 12 (noon local): require forecast in the afternoon when cooldown matters.
TEMP_LOW_YES_REQUIRE_FORECAST_AFTER_LOCAL_HOUR: int = int(
    os.environ.get("TEMP_LOW_YES_REQUIRE_FORECAST_AFTER_LOCAL_HOUR", "12")
)

# ---------------------------------------------------------------------------
# Source-tier constants
# ---------------------------------------------------------------------------

_OBS_CONFIRMED = frozenset({"noaa_observed", "nws_climo", "metar"})
# High-confidence tier that also includes NWS alert signals.
# Used as the pass-through set in _filter_weather_opportunities and
# _apply_forecast_consensus — these sources bypass the forecast consensus
# check and always pass through unchanged.
_PASS_THROUGH_SOURCES = _OBS_CONFIRMED | frozenset({"nws_alert"})
# Forecast sources treated as unreliable for solo/same-day trading.
# May still vote in consensus but cannot trade solo without corroboration.
_FORECAST_UNRELIABLE = frozenset({"open_meteo", "weatherapi"})
# Source priority for selecting the "best" source when multiple agree.
# Lower number = higher priority.  Sources absent from this dict get 99.
_FORECAST_SOURCE_PRIORITY: dict[str, int] = {
    "hrrr":       0,
    "noaa":       1,
    "nws_hourly": 2,
    "noaa_day2":  3,
    "noaa_day3":  4,
    "noaa_day4":  5,
    "noaa_day5":  6,
    "noaa_day6":  7,
    "noaa_day7":  8,
    "open_meteo": 9,
    "weatherapi": 10,
}


# ---------------------------------------------------------------------------
# Weather gate helpers
# ---------------------------------------------------------------------------

def _gate_date_alignment(
    opp: "NumericOpportunity",
    now: "datetime",
) -> bool:
    """Return False if opp should be dropped due to date mismatch, True otherwise."""
    if opp.as_of:
        try:
            as_of_utc = parse_iso_dt(opp.as_of)
            as_of_et_date = as_of_utc.astimezone(_ET).date()
            market_date = _ticker_date(opp.market_ticker)
            if market_date is not None and market_date != as_of_et_date:
                logging.debug(
                    "NOAA date guard: dropped %s — market date %s ≠ data ET date %s",
                    opp.market_ticker, market_date, as_of_et_date,
                )
                return False
        except (ValueError, AttributeError):
            pass
    elif opp.source in ("noaa_observed", "metar", "nws_climo"):
        _city_tz_dg = _CITY_TZ.get(opp.metric)
        if _city_tz_dg is not None:
            _local_date_dg = now.astimezone(_city_tz_dg).date()
            _mkt_date_dg = _ticker_date(opp.market_ticker)
            if _mkt_date_dg is not None and _mkt_date_dg != _local_date_dg:
                logging.debug(
                    "NOAA date guard (no as_of): dropped %s — market %s ≠ local %s",
                    opp.market_ticker, _mkt_date_dg, _local_date_dg,
                )
                return False
    return True


def _gate_forecast_source(
    opp: "NumericOpportunity",
    hrrr_hourly_highs: "dict[str, float] | None",
    observed_values: "dict[str, float] | None",
    opp_log,
) -> bool:
    """Return True to keep this forecast-source opp, False to suppress.

    Applies: edge gate, morning observation gap gate, HRRR spread gate.
    """
    _min_edge = _resolve_min_edge(
        opp.source, opp.direction,
        metric=opp.metric, implied_outcome=opp.implied_outcome,
    )
    if opp.edge < _min_edge:
        if opp_log is not None:
            opp_log.log_suppression(
                ticker=opp.market_ticker,
                source=opp.source,
                gate="edge_min",
                metric=opp.metric,
                edge_f=opp.edge,
                value=opp.data_value,
                strike=opp.strike,
                yes_bid=int(opp.current_market_price) if isinstance(opp.current_market_price, (int, float)) else None,
                note=f"min_edge={_min_edge:.1f} direction={opp.direction}",
            )
        return False

    # Morning observation gap gate: block forecast YES when observed is far below strike.
    if (
        opp.implied_outcome == "YES"
        and not opp.source.startswith("noaa_day")
        and MORNING_OBS_GAP_F > 0
        and observed_values is not None
        and opp.strike is not None
    ):
        obs_val = observed_values.get(opp.metric)
        if obs_val is not None and (opp.strike - obs_val) > MORNING_OBS_GAP_F:
            logging.debug(
                "Morning gate: suppressed %s YES forecast — observed %.1f°F"
                " is %.1f°F below strike %.1f°F (gap > %.0f°F threshold)",
                opp.market_ticker, obs_val,
                opp.strike - obs_val, opp.strike, MORNING_OBS_GAP_F,
            )
            return False

    # HRRR spread gate: suppress when hourly and daily forecasts disagree on outcome.
    is_future_day = (
        opp.source.startswith("noaa_day")
        or (
            opp.source in ("open_meteo", "nws_hourly", "weatherapi")
            and opp.metadata.get("forecast_offset", 0) > 0
        )
    )
    if hrrr_hourly_highs and not is_future_day:
        hourly_high = hrrr_hourly_highs.get(opp.metric)
        if hourly_high is not None:
            spread = abs(opp.data_value - hourly_high)
            if spread >= HRRR_MAX_SPREAD_F:
                outcome_flips = True
                if opp.strike is not None:
                    if opp.direction == "over":
                        daily_yes = opp.data_value >= opp.strike
                        hourly_yes = hourly_high >= opp.strike
                    else:
                        daily_yes = opp.data_value <= opp.strike
                        hourly_yes = hourly_high <= opp.strike
                    outcome_flips = (daily_yes != hourly_yes)
                if outcome_flips:
                    logging.debug(
                        "HRRR gate: suppressed %s — daily %.1f°F vs hourly %.1f°F"
                        " (spread %.1f°F flips outcome across strike %.1f°F)",
                        opp.market_ticker, opp.data_value, hourly_high,
                        spread, opp.strike or 0.0,
                    )
                    if opp_log is not None:
                        opp_log.log_suppression(
                            ticker=opp.market_ticker,
                            source=opp.source,
                            gate="hrrr_spread",
                            metric=opp.metric,
                            edge_f=opp.edge,
                            value=opp.data_value,
                            strike=opp.strike,
                            yes_bid=int(opp.current_market_price) if isinstance(opp.current_market_price, (int, float)) else None,
                            note=f"hrrr_hourly={hourly_high:.1f} spread={spread:.1f}",
                        )
                    return False
                else:
                    logging.debug(
                        "HRRR spread %.1f°F on %s — daily %.1f°F and"
                        " hourly %.1f°F agree on outcome; allowing through",
                        spread, opp.market_ticker,
                        opp.data_value, hourly_high,
                    )
    return True


def _filter_weather_opportunities(
    opps: list[NumericOpportunity],
    markets: list[dict],
    hrrr_hourly_highs: dict[str, float] | None = None,
    observed_values: dict[str, float] | None = None,
    fc_low_by_metric: dict[str, float] | None = None,
    opp_log=None,
) -> list[NumericOpportunity]:
    """Apply source-specific quality gates to temperature (KXHIGH) opportunities.

    Three signal classes are handled:

    noaa_observed  (station max recorded since midnight)
        Ground truth — a hard lower bound on the day's high.
        YES: observed > strike → outcome locked; always surfaced (edge ≥ TEMP_OBSERVED_MIN_EDGE).
        NO:  only surfaced within TEMP_OBSERVED_MAX_HOURS of market close.

    nws_alert  (temperature parsed from an active NWS heat/cold warning)
        High-confidence directional signal — NWS issues warnings only when
        its own ensemble is highly confident.  Treated identically to
        noaa_observed: lower edge threshold, never gated by HRRR spread.

    noaa / open_meteo  (raw model forecast)
        Require edge >= TEMP_FORECAST_MIN_EDGE (7°F ≈ 2σ of day-1 MAE).
        Additionally gated by HRRR spread for same-day forecasts: if
        |daily_forecast − hourly_hrrr| >= HRRR_MAX_SPREAD_F the atmosphere
        is convectively uncertain and the forecast is unreliable.
        Extended-day sources (noaa_day2+, open_meteo day1+) skip the HRRR
        gate since today's HRRR data is irrelevant to future days.

    Morning observation gate (MORNING_OBS_GAP_F)
        For raw forecast YES signals, if the current noaa_observed max (since
        midnight) is more than MORNING_OBS_GAP_F below the strike, the trade
        is blocked: the observed reality is too far from the forecast for it
        to be credible.

    All non-temperature metrics pass through unchanged.
    """
    now = datetime.now(timezone.utc)

    # Build close_time index from the market list for quick lookup.
    close_dt_by_ticker: dict[str, datetime | None] = {}
    for m in markets:
        ticker = m.get("ticker", "")
        ct = m.get("close_time") or m.get("expiration_time")
        if ct:
            try:
                close_dt_by_ticker[ticker] = parse_iso_dt(ct)
            except (ValueError, AttributeError):
                close_dt_by_ticker[ticker] = None
        else:
            close_dt_by_ticker[ticker] = None

    # Obs-consensus pre-pass: for each (metric, strike), count how many
    # confirmed-observation sources (noaa_observed, nws_climo) already show
    # YES *and* pass the afternoon hour gate.  Used below to gate YES trades.
    obs_yes_sources: dict[tuple[str, float | None], set[str]] = {}
    if OBS_CONSENSUS_MIN > 1:
        for _o in opps:
            if (
                _o.source in _OBS_CONFIRMED
                and _o.metric.startswith(("temp_high", "temp_low"))
                and _o.implied_outcome == "YES"
            ):
                # Apply the same afternoon hour gate used in the main loop.
                _city_tz = _CITY_TZ.get(_o.metric)
                if _city_tz is not None:
                    if now.astimezone(_city_tz).hour < NOAA_OBS_YES_MIN_LOCAL_HOUR:
                        continue
                obs_yes_sources.setdefault((_o.metric, _o.strike), set()).add(_o.source)

    result: list[NumericOpportunity] = []
    for opp in opps:
        # Non-temperature metrics are unaffected.
        if not opp.metric.startswith(("temp_high", "temp_low")):
            result.append(opp)
            continue

        # Date guard: market date must match the data's local ET date.
        if not _gate_date_alignment(opp, now):
            continue

        if opp.source in _PASS_THROUGH_SOURCES:
            # High-confidence signals: ground truth (observed/climo) or NWS
            # warning.  Never gated by HRRR spread; direction-split edge threshold.
            if opp.direction == "over":
                min_edge = TEMP_OBSERVED_MIN_EDGE_OVER
            elif opp.direction == "between":
                # KXLOWT between YES needs a stricter edge: the observed running
                # minimum is a ceiling, not the confirmed daily low.  Overnight
                # cooling can push the temp below the band floor before settlement.
                if (
                    KXLOWT_OBS_BETWEEN_YES_MIN_EDGE > 0
                    and opp.implied_outcome == "YES"
                    and opp.metric.startswith("temp_low_")
                ):
                    min_edge = KXLOWT_OBS_BETWEEN_YES_MIN_EDGE
                else:
                    min_edge = TEMP_OBSERVED_MIN_EDGE_BETWEEN
            else:
                min_edge = TEMP_OBSERVED_MIN_EDGE_UNDER
            if opp.edge < min_edge:
                continue
            # noaa_observed max-edge cap: very high edges signal a faulty sensor
            # reading (station reporting stale/wrong temp), not a genuine gap.
            if opp.source == "noaa_observed" and opp.edge > TEMP_OBSERVED_MAX_EDGE:
                logging.debug(
                    "noaa_observed max-edge cap: edge=%.1f°F > %.1f°F on %s — "
                    "likely sensor error; suppressed",
                    opp.edge, TEMP_OBSERVED_MAX_EDGE, opp.market_ticker,
                )
                continue

            if opp.implied_outcome == "YES":
                # Time-of-day gate for confirmed-observation YES signals.
                #
                # direction=over  (observed already EXCEEDS strike): local-date guard only.
                #   The daily max is a running maximum — once above the strike it
                #   can only stay above or climb further.  Outcome is locked the
                #   moment it is observed.  The 5°F edge threshold absorbs any
                #   station-mismatch risk.
                #   BUT: _fetch_observed_max_today uses midnight UTC as its window
                #   start.  For CDT cities (UTC-5) midnight UTC = 7 PM local, so at
                #   04:00 UTC the window captures *yesterday evening's* readings.
                #   The ET date guard rolls to the next day at midnight ET (04:00 UTC),
                #   letting a March-25-evening observed high slip through as a March-26
                #   YES signal.  The local-date guard below closes this gap for both
                #   directions.
                #
                # direction=between YES (observed IS inside the range): 4:30 PM local.
                #   Lower bound is confirmed (observed ≥ strike_lo), but before 4:30 PM
                #   the temperature could still rise above strike_hi and make YES lose.
                #   Same afternoon gate as direction=under to ensure the day's peak
                #   has passed before committing.
                #
                # direction=under (observed still BELOW strike): 4:30 PM local.
                #   The observed max is a lower bound, not the confirmed daily
                #   high.  Before 4:30 PM there are still hours of potential
                #   warming; this gate ensures the peak has passed and the
                #   temperature is in the cooling-off phase.
                if opp.source in _OBS_CONFIRMED and opp.direction == "over":
                    city_tz = _CITY_TZ.get(opp.metric)
                    if city_tz is not None:
                        local_dt = now.astimezone(city_tz)
                        _mkt_date = _ticker_date(opp.market_ticker)
                        if _mkt_date is not None and _mkt_date != local_dt.date():
                            logging.debug(
                                "Date guard (local): suppressed %s direction=over YES %s"
                                " — market date %s ≠ city local date %s",
                                opp.source, opp.market_ticker,
                                _mkt_date, local_dt.date(),
                            )
                            continue

                        # Morning gate for low-temp observed YES signals.
                        # The running daily min resets at local midnight and at
                        # that point equals the current temp — not the overnight
                        # low, which typically occurs at 4–6 AM.  Block until
                        # NOAA_OBS_LOW_PAST_LOCAL_HOUR (default 05:00) by which
                        # point the trough has passed and the running min is a
                        # confirmed floor.
                        if opp.metric.startswith("temp_low_"):
                            local_mins = local_dt.hour * 60 + local_dt.minute
                            min_mins = (NOAA_OBS_LOW_PAST_LOCAL_HOUR * 60
                                        + NOAA_OBS_LOW_PAST_LOCAL_MINUTE)
                            if local_mins < min_mins:
                                logging.debug(
                                    "Morning gate: suppressed %s low-temp YES %s"
                                    " — local time %02d:%02d < %02d:%02d"
                                    " (overnight low not yet confirmed)",
                                    opp.source, opp.market_ticker,
                                    local_dt.hour, local_dt.minute,
                                    min_mins // 60, min_mins % 60,
                                )
                                continue

                            # Forecast floor gate: suppress YES if tonight's NWS
                            # forecast low is within striking distance of the
                            # strike.  Evening cooling after sunset can push the
                            # final daily min below the morning trough — the
                            # morning gate passes but the signal is still unsafe.
                            # 0.5°F buffer: NWS rounds to integer; need forecast
                            # ≥ strike+1 to guarantee official low > strike.
                            if fc_low_by_metric is not None and opp.strike is not None:
                                _fc_low = fc_low_by_metric.get(opp.metric)
                                if _fc_low is None and TEMP_LOW_YES_REQUIRE_FORECAST:
                                    _past_gate_hour = (
                                        local_dt.hour
                                        >= TEMP_LOW_YES_REQUIRE_FORECAST_AFTER_LOCAL_HOUR
                                    )
                                    if _past_gate_hour:
                                        logging.debug(
                                            "Forecast floor gate: suppressed noaa_observed YES %s"
                                            " — no tonight forecast after %02d:00 local"
                                            " (TEMP_LOW_YES_REQUIRE_FORECAST=true)",
                                            opp.market_ticker,
                                            TEMP_LOW_YES_REQUIRE_FORECAST_AFTER_LOCAL_HOUR,
                                        )
                                        continue
                                    # Before the gate hour: morning trough is the primary
                                    # signal; allow through without forecast.
                                    logging.debug(
                                        "Forecast floor gate: allowing noaa_observed YES %s"
                                        " without forecast — before %02d:00 local (%02d:%02d)",
                                        opp.market_ticker,
                                        TEMP_LOW_YES_REQUIRE_FORECAST_AFTER_LOCAL_HOUR,
                                        local_dt.hour, local_dt.minute,
                                    )
                                if (
                                    _fc_low is not None
                                    and _fc_low < opp.strike + TEMP_LOW_YES_FORECAST_BUFFER_F
                                ):
                                    logging.debug(
                                        "Forecast floor gate: suppressed noaa_observed YES %s"
                                        " — tonight forecast %.1f°F < strike+buf %.1f°F"
                                        " (strike=%.1f°F, buf=%.1f°F)",
                                        opp.market_ticker, _fc_low,
                                        opp.strike + TEMP_LOW_YES_FORECAST_BUFFER_F,
                                        opp.strike, TEMP_LOW_YES_FORECAST_BUFFER_F,
                                    )
                                    continue

                if opp.source in _OBS_CONFIRMED and opp.direction in ("under", "between"):
                    city_tz = _CITY_TZ.get(opp.metric)
                    if city_tz is not None:
                        local_dt = now.astimezone(city_tz)
                        local_mins = local_dt.hour * 60 + local_dt.minute
                        _p75 = _PEAK_P75_MINUTES.get(opp.metric, {}).get(local_dt.month)
                        min_mins = _p75 if _p75 is not None else (
                            NOAA_OBS_PEAK_PAST_LOCAL_HOUR * 60 + NOAA_OBS_PEAK_PAST_LOCAL_MINUTE
                        )

                        # Local-date guard: after midnight local time an observed
                        # reading is the overnight floor, not a confirmed daily high.
                        # The market must be for *today* in the city's timezone —
                        # if it's already past midnight locally the date guard at the
                        # top of this loop uses the ET date which can roll ahead of
                        # the city's local date, letting tomorrow's market slip through.
                        _mkt_date = _ticker_date(opp.market_ticker)
                        if _mkt_date is not None and _mkt_date != local_dt.date():
                            logging.debug(
                                "Date guard (local): suppressed %s direction=%s YES %s"
                                " — market date %s ≠ city local date %s",
                                opp.source, opp.direction, opp.market_ticker,
                                _mkt_date, local_dt.date(),
                            )
                            continue

                        if local_mins < min_mins:
                            logging.debug(
                                "Afternoon gate: suppressed %s YES %s"
                                " — local time %02d:%02d < %02d:%02d"
                                " (peak not yet confirmed)",
                                opp.source, opp.market_ticker,
                                local_dt.hour, local_dt.minute,
                                min_mins // 60, min_mins % 60,
                            )
                            if opp_log is not None:
                                opp_log.log_suppression(
                                    ticker=opp.market_ticker,
                                    source=opp.source,
                                    gate="obs_afternoon_gate",
                                    metric=opp.metric,
                                    edge_f=opp.edge,
                                    value=opp.data_value,
                                    strike=opp.strike,
                                    yes_bid=int(opp.current_market_price) if isinstance(opp.current_market_price, (int, float)) else None,
                                    note=f"local={local_dt.hour:02d}:{local_dt.minute:02d} need={min_mins//60:02d}:{min_mins%60:02d}",
                                )
                            continue

                        # After 4:30 PM the daily max is established — the upper
                        # bound of a "between" band is now locked.  Flag peak_past
                        # so score_p_yes uses a one-sided CDF (lower-boundary risk
                        # only) and the edge scorer measures clearance from
                        # strike_lo only, not the min of both distances.
                        if opp.direction == "between":
                            opp.peak_past = True

                    # Obs-consensus gate: require OBS_CONSENSUS_MIN distinct
                    # confirmed-observation sources to both show YES before
                    # trading.  Station mismatches appear in a single feed —
                    # requiring 2 sources eliminates most false positives.
                    if OBS_CONSENSUS_MIN > 1:
                        confirming = obs_yes_sources.get((opp.metric, opp.strike), set())
                        if len(confirming) < OBS_CONSENSUS_MIN:
                            logging.debug(
                                "Obs consensus gate: suppressed %s YES %s"
                                " — %d/%d obs sources confirm"
                                " (have: %s, need %d)",
                                opp.source, opp.market_ticker,
                                len(confirming), OBS_CONSENSUS_MIN,
                                confirming or "{none}", OBS_CONSENSUS_MIN,
                            )
                            continue

                    if opp.direction == "between" and getattr(opp, "peak_past", False):
                        # Forecast contradiction gate: even after the afternoon
                        # peak-past cutoff, check whether HRRR or NOAA's day-1
                        # forecast predicts the daily high will meet or exceed
                        # strike_hi.  If so, the temperature is expected to exit
                        # the band from above — suppress the YES.
                        #
                        # Uses two independent sources:
                        #   1. HRRR hourly max (most real-time, updates ~hourly)
                        #   2. opp.metadata["forecast_high"] (NOAA day-1 attached
                        #      to the noaa_observed DataPoint at fetch time)
                        #
                        # Why HRRR can still be wrong here: HRRR runs hourly and
                        # different model initializations can revise the predicted
                        # daily max up or down.  Using BOTH sources guards against
                        # a single-model revision that lowballs the peak.  If
                        # either source's prediction ≥ strike_hi, suppress.
                        if opp.strike_hi is not None:
                            _fc_ceiling_hits: dict[str, float] = {}
                            _hrrr_hi = (hrrr_hourly_highs or {}).get(opp.metric)
                            _noaa_meta_hi = (opp.metadata or {}).get("forecast_high")
                            # Kalshi resolves on the official NWS whole-degree
                            # high, so the effective band ceiling is strike_hi+0.5:
                            # any actual temp ≥ strike_hi+0.5 rounds to
                            # strike_hi+1 = outside the band.  HRRR and NOAA
                            # both report in whole degrees (from NWS grids), so
                            # the comparison ≥ strike_hi+0.5 is equivalent to
                            # "forecast rounds to a value above the band ceiling".
                            _ceil = opp.strike_hi + 0.5
                            if _hrrr_hi is not None and _hrrr_hi >= _ceil:
                                _fc_ceiling_hits["hrrr"] = _hrrr_hi
                            if _noaa_meta_hi is not None and _noaa_meta_hi >= _ceil:
                                _fc_ceiling_hits["noaa"] = _noaa_meta_hi
                            if _fc_ceiling_hits:
                                logging.debug(
                                    "Between-band YES fc-contradiction gate:"
                                    " suppressing %s %s — forecast(s) %s"
                                    " predict high ≥ strike_hi %.1f°F"
                                    " (observed=%.1f°F)",
                                    opp.source, opp.market_ticker,
                                    {k: f"{v:.1f}°F" for k, v in _fc_ceiling_hits.items()},
                                    opp.strike_hi, opp.data_value,
                                )
                                if opp_log is not None:
                                    opp_log.log_suppression(
                                        ticker=opp.market_ticker,
                                        source=opp.source,
                                        gate="between_yes_fc_contradict",
                                        metric=opp.metric,
                                        edge_f=opp.edge,
                                        value=opp.data_value,
                                        strike=opp.strike_hi,
                                        yes_bid=int(opp.current_market_price) if isinstance(opp.current_market_price, (int, float)) else None,
                                        note=f"fc={_fc_ceiling_hits} strike_hi={opp.strike_hi:.1f}",
                                    )
                                continue

                        logging.debug(
                            "%s LOCKED-BETWEEN-YES: %s  observed %.1f°F inside"
                            " [%.1f, %.1f], peak confirmed past %02d:%02d"
                            "  (edge %.1f°F above lo)",
                            opp.source.upper(), opp.market_ticker, opp.data_value,
                            opp.strike_lo or 0.0, opp.strike_hi or 0.0,
                            min_mins // 60, min_mins % 60, opp.edge,
                        )
                    else:
                        logging.debug(
                            "%s LOCKED-YES: %s  observed %.1f°F already exceeds strike"
                            "  (edge %.1f°F)",
                            opp.source.upper(), opp.market_ticker,
                            opp.data_value, opp.edge,
                        )
                else:
                    logging.debug(
                        "NWS ALERT-YES: %s  alert temp %.1f°F above strike"
                        "  (edge %.1f°F)",
                        opp.market_ticker, opp.data_value, opp.edge,
                    )
                result.append(opp)
            else:
                # NO signal.
                #
                # direction=over after 4:30 PM local: the observed max is BELOW
                # the strike and the day's peak is established — this is a
                # locked NO (mirror of the direction=between YES lock).  Flag it
                # with peak_past=True so score_numeric_opportunity() can override
                # the uncertainty sub-score to 1.0 instead of penalising the
                # market's already-low YES price.
                #
                # All other NO signals: only surface within TEMP_OBSERVED_MAX_HOURS
                # of close (market must be nearly over before a non-certain NO is
                # worth acting on).
                if opp.direction == "over":
                    city_tz = _CITY_TZ.get(opp.metric)
                    if city_tz is not None:
                        local_dt = now.astimezone(city_tz)
                        local_mins = local_dt.hour * 60 + local_dt.minute
                        _p75 = _PEAK_P75_MINUTES.get(opp.metric, {}).get(local_dt.month)
                        min_mins = _p75 if _p75 is not None else (
                            NOAA_OBS_PEAK_PAST_LOCAL_HOUR * 60 + NOAA_OBS_PEAK_PAST_LOCAL_MINUTE
                        )
                        _mkt_date = _ticker_date(opp.market_ticker)
                        if _mkt_date == local_dt.date() and local_mins >= min_mins:
                            opp.peak_past = True
                            logging.debug(
                                "%s LOCKED-NO: %s  observed %.1f°F < strike %.1f°F"
                                ", peak confirmed past %02d:%02d  (edge %.1f°F)",
                                opp.source.upper(), opp.market_ticker,
                                opp.data_value, opp.strike or 0.0,
                                min_mins // 60, min_mins % 60, opp.edge,
                            )
                            result.append(opp)
                            continue
                # Standard NO gate: only surface within TEMP_OBSERVED_MAX_HOURS of close.
                close_dt = close_dt_by_ticker.get(opp.market_ticker)
                if close_dt is not None:
                    hours_remaining = (close_dt - now).total_seconds() / 3600
                    if hours_remaining <= TEMP_OBSERVED_MAX_HOURS:
                        result.append(opp)

        else:
            # Raw forecast sources: edge gate + morning gap gate + HRRR spread gate.
            if not _gate_forecast_source(opp, hrrr_hourly_highs, observed_values, opp_log):
                continue
            result.append(opp)

    return result


def _apply_forecast_consensus(
    numeric_opps: list[NumericOpportunity],
    data_points: list[DataPoint],
    opp_log: OpportunityLog,
) -> tuple[list[NumericOpportunity], dict[str, float], dict[str, float]]:
    """Tiered forecast-source consensus filter for temperature markets.

    Returns (filtered_opps, obs_value, fc_low_by_metric).
    """
    # Build a direct lookup of noaa_observed values from raw data_points
    # so we can detect conflicts even when the observed opp was filtered out.
    _obs_value: dict[str, float] = {}
    for _dp in data_points:
        if _dp.source in ("noaa_observed", "metar") and _dp.metric.startswith(("temp_high", "temp_low")):
            # metar updates faster — prefer it over noaa_observed when both present
            if _dp.source == "metar" or _dp.metric not in _obs_value:
                _obs_value[_dp.metric] = _dp.value

    # Forecast low per temp_low metric from all model sources.
    # Keeps the most conservative (lowest) value across noaa, hrrr,
    # nws_hourly, and open_meteo so the KXLOWT contradiction gate has
    # the broadest possible coverage.  Used by _filter_weather_opportunities
    # and the inline KXLOWT gate below.
    _fc_low_by_metric: dict[str, float] = {}
    _FC_LOW_SOURCES = {"noaa", "hrrr", "nws_hourly", "open_meteo"}
    for _dp in data_points:
        if _dp.source in _FC_LOW_SOURCES and _dp.metric.startswith("temp_low_"):
            _existing = _fc_low_by_metric.get(_dp.metric)
            if _existing is None or _dp.value < _existing:
                _fc_low_by_metric[_dp.metric] = _dp.value

    by_key: dict[tuple[str, str], list[NumericOpportunity]] = collections.defaultdict(list)
    for opp in numeric_opps:
        by_key[(opp.metric, opp.market_ticker)].append(opp)

    consensus_opps: list[NumericOpportunity] = []
    for (metric, ticker), group in by_key.items():
        if not metric.startswith(("temp_high", "temp_low")):
            consensus_opps.extend(group)
            continue
        # noaa_observed, nws_climo, nws_alert are ground-truth / high-confidence
        # — always pass through the consensus check unchanged.
        # open_meteo is excluded from the unanimity check: it uses raw GFS output which
        # systematically underestimates cold-front timing/intensity and lags
        # NWS human-adjusted forecasts by 6-18 hours.  NOAA day-2+ is already
        # a multi-model blend (NBM) superior to raw GFS, so GFS should not
        # veto it.  Open-Meteo still runs and its DataPoints still count toward
        # corroboration when it agrees with NOAA, but it cannot block a NOAA
        # signal by disagreeing.
        _PASS_THROUGH = _PASS_THROUGH_SOURCES

        # Compute market date and same-day flag before building _EXCLUDE so
        # we can tune which sources participate in the vote.
        mkt_date = _ticker_date(ticker)
        today_et = datetime.now(_ET).date()
        is_same_day_mkt = (mkt_date is not None and mkt_date == today_et)

        # noaa_day2–7 draw from the same NWS forecast grid as nws_hourly
        # day+1/2, so counting both creates correlated double-counting.
        # Exception: for future-day markets (tomorrow+), only nws_hourly and
        # weatherapi vote, which makes a 1-1 tie structurally unbreakable.
        # Allowing noaa_day2 to join the vote gives 3 genuinely independent
        # data points (NWS hourly, WeatherAPI, NOAA NBM blend) so a majority
        # always emerges.  noaa_day2 on same-day markets fails date alignment
        # below anyway (as_of = tomorrow ≠ today's market), so this only
        # changes behaviour for tomorrow-closing markets.
        # open_meteo is excluded for same-day markets (HRRR hourly is better
        # and avoids GFS model noise intra-day), but included for future-day
        # markets where it is a genuinely independent source that can
        # corroborate NWS extended forecasts.  open_meteo is NOT derived from
        # the NWS NBM blending pipeline, making it genuinely independent.
        _EXCLUDE_BASE = ("noaa_day3", "noaa_day4",
                         "noaa_day5", "noaa_day6", "noaa_day7")
        _EXCLUDE = _EXCLUDE_BASE + (("noaa_day2", "open_meteo") if is_same_day_mkt else ())
        observed = [o for o in group if o.source in _PASS_THROUGH]
        forecasts = [o for o in group if o.source not in _PASS_THROUGH and o.source not in _EXCLUDE]

        # ---- KXLOWT observed-YES contradiction gate ----------------------------
        # For daily-low markets, a morning running-minimum above the strike does
        # NOT lock in a YES outcome — temperatures can still fall later in the day
        # (e.g. cold-front passage in Chicago in April).  Suppress noaa_observed /
        # metar YES signals when any forecast model predicts the daily low will be
        # within LOWT_FORECAST_GATE_BUFFER_F degrees of (or below) the strike.
        # The buffer (default 3°F ≈ NWS day-1 MAE) catches "dangerously close"
        # forecasts like 54°F vs 53°F strike where model uncertainty is material.
        if (
            NUMERIC_LOWT_FORECAST_GATE
            and metric.startswith("temp_low_")
            and "KXLOWT" in ticker
        ):
            _obs_yes = [
                o for o in observed
                if o.implied_outcome == "YES"
                and o.source in ("noaa_observed", "metar")
            ]
            if _obs_yes:
                _strike = min(
                    (o.strike for o in _obs_yes if o.strike is not None),
                    default=None,
                )
                _fc_low = _fc_low_by_metric.get(metric)
                if (
                    _strike is not None
                    and _fc_low is not None
                    and _fc_low < _strike + LOWT_FORECAST_GATE_BUFFER_F
                ):
                    logging.warning(
                        "KXLOWT forecast-contradiction gate: suppressing %s "
                        "observed YES for %s — forecast low %.1f°F < strike "
                        "%.1f°F + buffer %.1f°F",
                        ", ".join(o.source for o in _obs_yes),
                        ticker, _fc_low, _strike, LOWT_FORECAST_GATE_BUFFER_F,
                    )
                    for _suppressed_obs in _obs_yes:
                        opp_log.log_suppression(
                            ticker=ticker,
                            source=_suppressed_obs.source,
                            gate="kxlowt_fc_contra",
                            metric=metric,
                            edge_f=_suppressed_obs.edge,
                            value=_suppressed_obs.data_value,
                            strike=_strike,
                            yes_bid=int(_suppressed_obs.current_market_price) if isinstance(_suppressed_obs.current_market_price, (int, float)) else None,
                            note=f"fc_low={_fc_low:.1f} buf={LOWT_FORECAST_GATE_BUFFER_F:.1f}",
                        )
                    observed = [o for o in observed if o not in _obs_yes]

        # ---- KXLOWT obs-YES positive confirmation gate --------------------
        # After the contradiction gate, if any noaa_observed/metar YES
        # signals survived, require at least KXLOWT_OBS_YES_FC_CONFIRM_MIN
        # forecast sources to actively predict fc_low > strike (not just
        # "not contradicting" — at least one model must clearly confirm YES).
        if (
            KXLOWT_OBS_YES_FC_CONFIRM_MIN > 0
            and metric.startswith("temp_low_")
            and "KXLOWT" in ticker
        ):
            _surviving_obs_yes = [
                o for o in observed
                if o.implied_outcome == "YES"
                and o.source in ("noaa_observed", "metar")
            ]
            if _surviving_obs_yes:
                _confirm_strike = min(
                    (o.strike for o in _surviving_obs_yes if o.strike is not None),
                    default=None,
                )
                if _confirm_strike is not None:
                    # Count distinct forecast sources predicting fc_low > strike
                    _fc_confirming_sources = {
                        _dp.source for _dp in data_points
                        if _dp.source in _FC_LOW_SOURCES
                        and _dp.metric == metric
                        and _dp.value > _confirm_strike
                    }
                    _fc_confirming = len(_fc_confirming_sources)
                    _suppress = False
                    _suppress_reason = ""

                    if _fc_confirming < KXLOWT_OBS_YES_FC_CONFIRM_MIN:
                        _suppress = True
                        _suppress_reason = (
                            f"only {_fc_confirming} forecast source(s) confirm"
                            f" fc_low > {_confirm_strike:.1f}°F (need"
                            f" {KXLOWT_OBS_YES_FC_CONFIRM_MIN})"
                        )
                    elif (
                        KXLOWT_OBS_YES_NEAR_TERM_REQUIRED
                        and not (_fc_confirming_sources & _KXLOWT_NEAR_TERM_SOURCES)
                    ):
                        # Total count is sufficient but no near-term model
                        # (hrrr/nws_hourly) is among the confirmers.  Near-term
                        # models have 2–3°F MAE vs 3–5°F for global day-ahead
                        # models and are essential for overnight cold-front timing.
                        _suppress = True
                        _suppress_reason = (
                            f"no near-term model (hrrr/nws_hourly) confirms"
                            f" fc_low > {_confirm_strike:.1f}°F —"
                            f" confirming sources: {_fc_confirming_sources or 'none'}"
                        )

                    if _suppress:
                        logging.debug(
                            "KXLOWT obs-YES confirmation gate: suppressing %s YES %s"
                            " — %s",
                            ", ".join(o.source for o in _surviving_obs_yes),
                            ticker, _suppress_reason,
                        )
                        observed = [o for o in observed if o not in _surviving_obs_yes]

        # Date-alignment pre-filter: remove forecast DataPoints whose as_of
        # date does not match the market's resolution date.  Without this,
        # NOAA day-1 (as_of = today) and NOAA day-2 (as_of = tomorrow) both
        # appear in the same (metric, ticker) group for a tomorrow-closing
        # market and disagree with each other, triggering a false "disagree"
        # block.  Pass-through (observed) signals are exempt — they reflect
        # the current day's running maximum and are always relevant.
        if mkt_date is not None:
            aligned: list[NumericOpportunity] = []
            for _fc in forecasts:
                if not _fc.as_of:
                    aligned.append(_fc)
                    continue
                try:
                    _fc_date = (
                        parse_iso_dt(_fc.as_of)
                        .astimezone(_ET)
                        .date()
                    )
                    if _fc_date == mkt_date:
                        aligned.append(_fc)
                except (ValueError, AttributeError):
                    aligned.append(_fc)
            forecasts = aligned

        # Multiple observed sources (noaa_observed, nws_observed) can fire on
        # the same (metric, ticker) in the same poll cycle.  Keep only the
        # highest-edge signal so downstream trade_executor sees one clean
        # opportunity rather than duplicate orders for the same market.
        seen_obs: dict[str, NumericOpportunity] = {}
        for _obs in observed:
            key = f"{_obs.metric}|{_obs.market_ticker}"
            if key not in seen_obs or abs(_obs.edge) > abs(seen_obs[key].edge):
                seen_obs[key] = _obs
        consensus_opps.extend(seen_obs.values())

        if not forecasts:
            continue

        # Tiered consensus — replaces strict unanimity which became
        # intractable once 4 sources were in the blocking pool.
        #
        # Same-day markets: nws_hourly and hrrr update every hour and
        # track cold fronts in real-time.  NOAA updates only 4×/day and
        # can be 10-20°F stale.  When same-day real-time sources agree,
        # use their direction.  Only override if ALL slower daily sources
        # also oppose (i.e., unanimous disagreement across 2+ daily sources).
        #
        # Future-day markets: NOAA multi-model blend is most reliable at
        # longer horizons.  Use majority vote among all forecasts; a tie
        # is too uncertain to trade.
        _REALTIME_SRCS = frozenset(("nws_hourly", "hrrr"))
        # mkt_date, today_et, is_same_day_mkt already computed above.

        realtime_fc = [o for o in forecasts if o.source in _REALTIME_SRCS]
        daily_fc = [o for o in forecasts if o.source not in _REALTIME_SRCS]

        if is_same_day_mkt and realtime_fc:
            # Real-time sources must agree with each other first.
            rt_outcomes = {o.implied_outcome for o in realtime_fc}
            if len(rt_outcomes) > 1:
                logging.debug(
                    "Consensus filter: real-time sources split on %s %s"
                    " — skipping (sources: %s)",
                    metric, ticker, {o.source for o in realtime_fc},
                )
                continue
            forecast_outcome = next(iter(rt_outcomes))
            # Only block when ALL daily-update sources (e.g. NOAA + WeatherAPI)
            # oppose the real-time direction.  A lone NOAA disagreement (stale
            # zone forecast) should not override nws_hourly+hrrr consensus.
            daily_oppose = [o for o in daily_fc if o.implied_outcome != forecast_outcome]
            if len(daily_oppose) == len(daily_fc) and len(daily_fc) >= 2:
                logging.debug(
                    "Consensus filter: all daily sources %s oppose"
                    " real-time (%s) on %s %s — skipping",
                    {o.source for o in daily_oppose},
                    forecast_outcome, metric, ticker,
                )
                continue
        else:
            # Future-day (or no real-time source present): NWS-primary logic.
            #
            # nws_hourly and noaa_day2 are both NWS products (hourly zone
            # forecast and NBM extended blend respectively) and are the most
            # reliable multi-day forecast sources.  open_meteo (raw ECMWF/GFS)
            # and weatherapi (third-party model) act as independent validators.
            #
            # If NWS sources agree with each other, treat their direction as
            # primary and only block if ALL external validators unanimously
            # oppose — the same asymmetric rule used on same-day markets where
            # nws_hourly+hrrr are primary.  A 2-2 tie (NWS vs external) is
            # resolved in favour of NWS rather than leaving the market untraded.
            #
            # If NWS sources disagree or are absent, fall back to majority vote.
            _NWS_SRCS = frozenset(("nws_hourly", "noaa_day2"))
            _EXT_SRCS = frozenset(("open_meteo", "weatherapi"))
            nws_fc = [o for o in forecasts if o.source in _NWS_SRCS]
            ext_fc = [o for o in forecasts if o.source in _EXT_SRCS]
            nws_outcomes = {o.implied_outcome for o in nws_fc}

            if len(nws_fc) >= 2 and len(nws_outcomes) == 1:
                # Both NWS sources agree → use NWS direction.
                forecast_outcome = next(iter(nws_outcomes))
                ext_oppose = [o for o in ext_fc if o.implied_outcome != forecast_outcome]
                if ext_oppose and len(ext_oppose) == len(ext_fc) and len(ext_fc) >= 2:
                    # ALL external models unanimously oppose NWS → too uncertain.
                    logging.debug(
                        "Consensus filter: all external models %s oppose"
                        " NWS primary (%s) on %s %s — skipping",
                        {o.source for o in ext_oppose},
                        forecast_outcome, metric, ticker,
                    )
                    continue
                logging.debug(
                    "Consensus filter: NWS primary (%s) on %s %s"
                    " — %d external validator(s) oppose but not unanimous; allowing",
                    forecast_outcome, metric, ticker, len(ext_oppose),
                )
            else:
                # NWS sources disagree or absent: plain majority vote.
                yes_count = sum(1 for o in forecasts if o.implied_outcome == "YES")
                no_count = sum(1 for o in forecasts if o.implied_outcome == "NO")
                if yes_count == no_count:
                    logging.debug(
                        "Consensus filter: forecasts tied on %s %s — skipping"
                        " (sources: %s yes=%d no=%d)",
                        metric, ticker,
                        {o.source for o in forecasts}, yes_count, no_count,
                    )
                    continue
                forecast_outcome = "YES" if yes_count > no_count else "NO"
        # Cross-check against raw noaa_observed data even when that
        # observation is too expensive to trade (not in numeric_opps).
        #
        # IMPORTANT: only valid for same-day markets.  For future-day markets
        # (tomorrow or later), today's observed temperature has no bearing on
        # tomorrow's forecast — of course today's high is below tomorrow's
        # warm-day strike.  Applying this check to future-day markets silently
        # suppressed ALL future-day YES forecasts where today's temp hadn't
        # yet reached tomorrow's strike (e.g. Austin T86: today 72°F → "NO"
        # conflicts with noaa_day2+weatherapi "YES" for tomorrow → suppressed).
        obs_val = _obs_value.get(metric)
        if obs_val is not None and not observed and is_same_day_mkt:
            ref = forecasts[0]
            if ref.direction == "over" and ref.strike is not None:
                obs_outcome = "YES" if obs_val >= ref.strike else "NO"
            elif ref.direction == "under" and ref.strike is not None:
                obs_outcome = "YES" if obs_val <= ref.strike else "NO"
            else:
                obs_outcome = None
            if obs_outcome is not None and obs_outcome != forecast_outcome:
                logging.debug(
                    "Consensus filter: noaa_observed (%.1f°F → %s) conflicts"
                    " with forecast (%s) on %s %s — suppressing forecast",
                    obs_val, obs_outcome, forecast_outcome, metric, ticker,
                )
                continue
        # Cross-source corroboration gate: for YES forecast signals,
        # require at least FORECAST_CORROBORATION_MIN distinct sources to
        # agree.  Lone signals (only one model sees it) are model noise.
        #
        # Special rule: open_meteo (raw GFS) may never trade solo —
        # it systematically underestimates cold-front timing/intensity and
        # is already embedded in NOAA's blended forecast.  A lone
        # open_meteo YES is suppressed regardless of FORECAST_CORROBORATION_MIN.
        # NOAA-family sources (noaa, noaa_day2 … noaa_day7) may trade solo
        # when FORECAST_CORROBORATION_MIN=1 since they are already a
        # multi-model blend with human forecaster adjustments.
        if forecast_outcome == "YES":
            yes_sources = {o.source for o in forecasts if o.implied_outcome == "YES"}
            # obs_trajectory is an observed-trend signal (derived from real METAR
            # readings) — treated alongside noaa/hrrr as a trusted source.
            noaa_yes = {
                s for s in yes_sources
                if s.startswith("noaa") or s in ("hrrr", "obs_trajectory")
            }
            # Sources that may never trade solo (unreliable standalone forecasts):
            # - open_meteo: raw GFS, systematically underestimates cold-front timing
            # - weatherapi: commercial aggregator with demonstrated day+0/+1 errors
            #   (7°F+ same-day, >16°F next-day). Can still vote in consensus.
            _SOLO_BLOCKED = _FORECAST_UNRELIABLE
            gfs_only = not noaa_yes  # True when no NOAA/HRRR/obs_trajectory source is in YES set
            solo_unreliable = len(yes_sources) == 1 and yes_sources <= _SOLO_BLOCKED
            if (gfs_only or solo_unreliable) and len(yes_sources) < 2:
                logging.debug(
                    "Corroboration gate: lone %s YES on %s %s — "
                    "unreliable source may not trade solo; suppressed",
                    ", ".join(yes_sources), metric, ticker,
                )
                _rep = next((o for o in forecasts if o.implied_outcome == "YES"), forecasts[0])
                opp_log.log_suppression(
                    ticker=ticker, source=",".join(sorted(yes_sources)), gate="corr_solo_yes",
                    metric=metric, edge_f=_rep.edge, value=_rep.data_value, strike=_rep.strike,
                    yes_bid=int(_rep.current_market_price) if isinstance(_rep.current_market_price, (int, float)) else None,
                    note=f"yes_sources={sorted(yes_sources)}",
                )
                continue
            # obs_trajectory is self-corroborating: it derives from real observed
            # METAR readings so a lone signal is accepted without requiring an
            # additional model source.  All other trusted sources (noaa, hrrr)
            # still require FORECAST_CORROBORATION_MIN when trading solo.
            obs_traj_solo = yes_sources == {"obs_trajectory"}
            # Use a stricter threshold for KXLOWT — daily lows are harder
            # to forecast and we now have enough sources to require stronger
            # consensus (hrrr, nws_hourly, open_meteo all emit temp_low_*).
            _corr_min = (
                KXLOWT_FORECAST_CORROBORATION_MIN
                if metric.startswith("temp_low_") and "KXLOWT" in ticker
                else FORECAST_CORROBORATION_MIN
            )
            if not gfs_only and not obs_traj_solo and _corr_min > 1:
                if len(yes_sources) < _corr_min:
                    logging.debug(
                        "Corroboration gate: %s YES on %s %s"
                        " (need %d sources%s, have %d) — suppressed",
                        next(iter(yes_sources)), metric, ticker,
                        _corr_min,
                        " for KXLOWT" if _corr_min != FORECAST_CORROBORATION_MIN else "",
                        len(yes_sources),
                    )
                    _rep = next((o for o in forecasts if o.implied_outcome == "YES"), forecasts[0])
                    opp_log.log_suppression(
                        ticker=ticker, source=",".join(sorted(yes_sources)), gate="corr_lone_rt_no" if is_same_day_mkt else "corr_lone_daily_no",
                        metric=metric, edge_f=_rep.edge, value=_rep.data_value, strike=_rep.strike,
                        yes_bid=int(_rep.current_market_price) if isinstance(_rep.current_market_price, (int, float)) else None,
                        note=f"yes_sources={sorted(yes_sources)} need={_corr_min}",
                    )
                    continue
            # Hard gate: noaa_day2…day7 are all from the same NWS extended
            # product and are NOT independent of each other.  Even with
            # FORECAST_CORROBORATION_MIN=1, require at least one genuinely
            # independent source (noaa same-day, hrrr, open_meteo)
            # before acting on a day-ahead NWS forecast signal.
            # These forecasts update infrequently and can be 12+ hours stale
            # by the time the market moves — a single stale model run is not
            # enough justification to trade.
            _NOAA_FUTURE_PREFIXES = (
                "noaa_day2", "noaa_day3", "noaa_day4",
                "noaa_day5", "noaa_day6", "noaa_day7",
            )
            _noaa_future = {
                s for s in yes_sources
                if any(s == p or s.startswith(p + "_") for p in _NOAA_FUTURE_PREFIXES)
            }
            if _noaa_future and not (yes_sources - _noaa_future):
                logging.debug(
                    "Corroboration gate: day-ahead NOAA-only YES on %s %s"
                    " (%s) — no independent model confirms; suppressed",
                    metric, ticker, ", ".join(sorted(_noaa_future)),
                )
                continue

        # NO-side corroboration gate (future-day markets).
        # YES signals require FORECAST_CORROBORATION_MIN sources; NO had no
        # equivalent, which is why all 3 noaa_day2 NO trades were disasters —
        # a lone NWS extended-forecast saying "temp won't reach the strike"
        # was allowed through with zero independent confirmation.
        # Canonical failures: trades #185 (-135¢), #188 (-69¢), #189 (-4¢).
        # Now require the same count as YES.  With open_meteo now in the
        # forecast pool for future-day markets, noaa_day2 + open_meteo
        # provides a genuinely independent NWS+ECMWF two-source signal.
        if forecast_outcome == "NO" and not is_same_day_mkt:
            no_forecasts_fday = [o for o in forecasts if o.implied_outcome == "NO"]
            no_sources_fday = {o.source for o in no_forecasts_fday}
            # weatherapi is demoted to corroboration-only (same as open_meteo).
            # A weatherapi-only NO on a future-day market is suppressed regardless
            # of FORECAST_CORROBORATION_MIN.
            if len(no_sources_fday) == 1 and no_sources_fday <= {"open_meteo", "weatherapi"}:
                logging.debug(
                    "Corroboration gate: lone %s NO on future-day %s %s — "
                    "unreliable source may not trade solo; suppressed",
                    ", ".join(no_sources_fday), metric, ticker,
                )
                _rep = next((o for o in no_forecasts_fday), forecasts[0])
                opp_log.log_suppression(
                    ticker=ticker, source=",".join(sorted(no_sources_fday)), gate="corr_future_lone",
                    metric=metric, edge_f=_rep.edge, value=_rep.data_value, strike=_rep.strike,
                    yes_bid=int(_rep.current_market_price) if isinstance(_rep.current_market_price, (int, float)) else None,
                    note=f"no_sources={sorted(no_sources_fday)} unreliable_solo",
                )
                continue
            if len(no_sources_fday) < FORECAST_CORROBORATION_MIN:
                logging.debug(
                    "Corroboration gate: lone %s NO on future-day %s %s"
                    " (need %d sources, have %d) — suppressed",
                    ", ".join(sorted(no_sources_fday)), metric, ticker,
                    FORECAST_CORROBORATION_MIN, len(no_sources_fday),
                )
                _rep = next((o for o in no_forecasts_fday), forecasts[0])
                opp_log.log_suppression(
                    ticker=ticker, source=",".join(sorted(no_sources_fday)), gate="corr_lone_daily_no",
                    metric=metric, edge_f=_rep.edge, value=_rep.data_value, strike=_rep.strike,
                    yes_bid=int(_rep.current_market_price) if isinstance(_rep.current_market_price, (int, float)) else None,
                    note=f"no_sources={sorted(no_sources_fday)} need={FORECAST_CORROBORATION_MIN}",
                )
                continue
            # For "between" band NO signals, sources can agree on NO for
            # opposite reasons: one says too hot (above band), another says
            # too cold (below band).  This is contradictory, not corroboration.
            # Require all NO sources to agree on which side of the band the
            # forecast falls (all above strike_hi, or all below strike_lo).
            ref_opp = next((o for o in no_forecasts_fday), None)
            if (
                ref_opp is not None
                and ref_opp.direction == "between"
                and ref_opp.strike_lo is not None
                and ref_opp.strike_hi is not None
            ):
                above = [o for o in no_forecasts_fday if o.data_value > ref_opp.strike_hi]
                below = [o for o in no_forecasts_fday if o.data_value < ref_opp.strike_lo]
                if above and below:
                    logging.debug(
                        "Corroboration gate: contradictory NO on between %s %s"
                        " — sources disagree on which side of band"
                        " (above=%s, below=%s); suppressed",
                        metric, ticker,
                        [o.source for o in above],
                        [o.source for o in below],
                    )
                    continue

        # NO-side corroboration gate (same-day markets).
        # A lone real-time source (nws_hourly only, no HRRR) calling NO
        # on a same-day market carries substantial late-afternoon risk:
        # hourly forecast grids lag reality by 1–3 hours and the daily
        # high may already be locked in.  Require at least one daily
        # source (noaa) to corroborate the NO direction. weatherapi is demoted
        # to corroboration-only and cannot act as a qualifying daily source here.
        # Trade #200 is the canonical failure: nws_hourly alone fired NO
        # at 4:11 PM ET; market resolved YES 7 minutes later.
        # HRRR is exempt: it runs hourly with data assimilation (no lag),
        # has scored 0.92 on overnight NO calls, and the comment above
        # explicitly describes the gate as covering nws_hourly only.
        if forecast_outcome == "NO" and is_same_day_mkt:
            no_sources = {o.source for o in forecasts if o.implied_outcome == "NO"}
            rt_no    = {s for s in no_sources if s in _REALTIME_SRCS}
            daily_no = {s for s in no_sources if s not in _REALTIME_SRCS}
            # Block lone real-time (nws_hourly without HRRR): hourly grids
            # lag reality by 1–3h; daily high may already be locked.
            if (
                rt_no and not daily_no and len(rt_no) < 2
                and rt_no != frozenset({"hrrr"})  # HRRR alone is high-quality; exempt
            ):
                logging.debug(
                    "Corroboration gate: lone real-time NO (%s) on same-day"
                    " %s %s with no daily-source agreement — suppressed",
                    rt_no, metric, ticker,
                )
                continue
            # Block lone unreliable daily-model sources (weatherapi, open_meteo)
            # on same-day markets.  These sources resolve at daily model cadence
            # (not intraday) and carry no intraday observation — they cannot
            # reliably call NO on a same-day market without real-time support.
            # Trade #12 (Boston KXHIGHT NO) was driven solely by weatherapi and
            # stopped out prematurely at −$0.44; the market resolved NO 10 min later.
            _DAILY_UNRELIABLE = _FORECAST_UNRELIABLE
            if (
                not rt_no
                and daily_no <= _DAILY_UNRELIABLE
                and len(daily_no) == 1
            ):
                logging.debug(
                    "Corroboration gate: lone unreliable daily-model NO (%s)"
                    " on same-day %s %s — suppressed (no real-time corroboration)",
                    ", ".join(daily_no), metric, ticker,
                )
                continue

        # Forecast consensus reached — select the most authoritative source
        # as the primary, rather than max-edge (which would elevate
        # weatherapi/open_meteo above NOAA/HRRR when their edge is higher).
        # weatherapi and open_meteo are corroboration-only; they should never
        # be the logged "source" that drove the trade.
        agreeing = [o for o in forecasts if o.implied_outcome == forecast_outcome]
        best = min(agreeing, key=lambda o: _FORECAST_SOURCE_PRIORITY.get(o.source, 99))
        best.corroborating_sources = [
            o.source for o in agreeing if o.source != best.source
        ]
        if len(agreeing) > 1:
            _edges = [o.edge for o in agreeing]
            _vals  = [o.data_value for o in agreeing]
            best.consensus_meta = {
                "source_count":   len(agreeing),
                "min_edge_f":     min(_edges),
                "max_edge_f":     max(_edges),
                "model_spread_f": (max(_vals) - min(_vals)) if len(_vals) > 1 else 0.0,
                "corroborators":  best.corroborating_sources,
            }
        consensus_opps.append(best)
    return consensus_opps, _obs_value, _fc_low_by_metric
