"""Backtest: does running min at P75 time being warmer than GFS forecast predict
that the final daily low stays warm?  (Analog of backtest_noaa_gate.py for lows.)

Hypothesis for KXLOWT NO gate:
  When running min at P75 > GFS predicted daily min → temperature hasn't cooled
  as fast as model expected → final daily low more likely to stay warm →
  supports NO (final low stays above the band ceiling).

Data sources:
  - GFS daily min forecast: Open-Meteo historical forecast API (2022–2025)
    Proxy for NWS morning forecast.
  - IEM ASOS hourly observations: compute running min at P75 time.
  - Actual daily low: min of all ASOS obs for the calendar day (midnight-to-midnight
    local), a close proxy for NWS CLI official low.

Key metrics:
  overshoot = running_min_at_p75 − gfs_daily_min_forecast
              (positive = warmer than forecast = less cooling than expected)
  continued = running_min_at_p75 − actual_daily_low
              (positive = more cooling happened after P75 was measured)

Question: when overshoot > 0, is "continued" lower (less additional cooling)?
A YES answer means the gate is predictive: warmer-than-GFS at P75 → low is in.

P75 times are read from data/overnight_low_analysis.csv (generated by
scripts/backtest_overnight_low_hour.py --dict).

Run:
  venv/bin/python scripts/backtest_noaa_gate_low.py
  venv/bin/python scripts/backtest_noaa_gate_low.py --start 2023-01-01 --end 2025-12-31
"""

import argparse
import asyncio
import csv
import io
import math
import os
import sys
from collections import defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

import aiohttp

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from kalshi_bot.cities import LOW_CITIES
from scripts.build_forecast_calibration import IEM_STATIONS

CACHE_DIR = "data/cache/noaa_gate_low_backtest"
os.makedirs(CACHE_DIR, exist_ok=True)

LOW_ANALYSIS_CSV = Path("data/overnight_low_analysis.csv")

# Only low-temp metrics that have IEM stations
LOW_METRICS = {k: v for k, v in LOW_CITIES.items() if k in IEM_STATIONS}


# ── Load P75 times from CSV ────────────────────────────────────────────────────

def load_p75_minutes() -> dict[str, dict[int, int]]:
    """Read P75 trough times from overnight_low_analysis.csv.

    Returns {metric: {month: minutes_since_local_midnight}}.
    """
    result: dict[str, dict[int, int]] = {}
    if not LOW_ANALYSIS_CSV.exists():
        print(
            f"WARNING: {LOW_ANALYSIS_CSV} not found. "
            "Run: venv/bin/python scripts/backtest_overnight_low_hour.py --dict",
            file=sys.stderr,
        )
        return result

    with LOW_ANALYSIS_CSV.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            metric = row["city_key"]
            month = int(row["month"])
            p75_str = row.get("p75", "")
            if not p75_str or ":" not in p75_str:
                continue
            h, m = p75_str.split(":")
            minutes = int(h) * 60 + int(m)
            result.setdefault(metric, {})[month] = minutes

    return result


# ── Data fetching ──────────────────────────────────────────────────────────────

async def fetch_gfs_daily_min(
    session: aiohttp.ClientSession,
    lat: float,
    lon: float,
    start: str,
    end: str,
    cache_key: str,
) -> dict[str, float]:
    """GFS predicted daily min temperature. Returns {date_str: fahrenheit}."""
    import json
    cache_path = os.path.join(CACHE_DIR, f"gfs_{cache_key}_{start}_{end}.json")
    if os.path.exists(cache_path):
        with open(cache_path) as f:
            return json.load(f)

    params = {
        "latitude": lat, "longitude": lon,
        "start_date": start, "end_date": end,
        "daily": "temperature_2m_min",
        "temperature_unit": "fahrenheit",
        "timezone": "UTC",
        "models": "gfs_seamless",
    }
    for attempt in range(3):
        try:
            async with session.get(
                "https://historical-forecast-api.open-meteo.com/v1/forecast",
                params=params, timeout=aiohttp.ClientTimeout(total=60),
            ) as resp:
                resp.raise_for_status()
                data = await resp.json()
            break
        except Exception as e:
            print(f"  [GFS] {cache_key} attempt {attempt+1}: {e}", file=sys.stderr)
            await asyncio.sleep(2)
    else:
        return {}

    daily = data.get("daily", {})
    dates = daily.get("time", [])
    vals = (
        daily.get("temperature_2m_min_gfs_seamless")
        or daily.get("temperature_2m_min") or []
    )
    result = {d: v for d, v in zip(dates, vals) if v is not None}

    with open(cache_path, "w") as f:
        json.dump(result, f)
    return result


async def fetch_iem_hourly(
    session: aiohttp.ClientSession,
    station: str,
    network: str,
    start: str,
    end: str,
    cache_key: str,
) -> dict[str, list[tuple[datetime, float]]]:
    """IEM ASOS hourly observations. Returns {date_str: [(utc_datetime, temp_f), ...]}."""
    cache_path = os.path.join(CACHE_DIR, f"iem_{cache_key}_{start}_{end}.csv")
    if os.path.exists(cache_path):
        with open(cache_path) as f:
            raw = f.read()
    else:
        s = datetime.fromisoformat(start)
        e = datetime.fromisoformat(end)
        url = (
            f"https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py"
            f"?station={station}&data=tmpf"
            f"&year1={s.year}&month1={s.month}&day1={s.day}"
            f"&year2={e.year}&month2={e.month}&day2={e.day}"
            f"&tz=UTC&format=comma&latlon=no&direct=yes&report_type=3"
        )
        for attempt in range(3):
            try:
                async with session.get(url, timeout=aiohttp.ClientTimeout(total=180)) as resp:
                    resp.raise_for_status()
                    raw = await resp.text()
                break
            except Exception as ex:
                print(f"  [IEM hourly] {station} attempt {attempt+1}: {ex}", file=sys.stderr)
                await asyncio.sleep(5)
        else:
            return {}
        with open(cache_path, "w") as f:
            f.write(raw)

    result: dict[str, list[tuple[datetime, float]]] = defaultdict(list)
    reader = csv.reader(io.StringIO(raw))
    for row in reader:
        if len(row) < 3 or row[0].startswith("#") or row[0] == "station":
            continue
        try:
            dt = datetime.strptime(row[1].strip(), "%Y-%m-%d %H:%M").replace(
                tzinfo=ZoneInfo("UTC")
            )
            temp = float(row[2].strip())
        except (ValueError, IndexError):
            continue
        date_str = dt.date().isoformat()
        result[date_str].append((dt, temp))

    return dict(result)


# ── Analysis helpers ───────────────────────────────────────────────────────────

def running_min_at_time(obs: list[tuple[datetime, float]], cutoff_utc: datetime) -> float | None:
    """Min temperature seen in obs up to and including cutoff_utc (local calendar day)."""
    vals = [t for dt, t in obs if dt <= cutoff_utc]
    return min(vals) if vals else None


def p75_utc(
    metric: str,
    d: date,
    tz: ZoneInfo,
    p75_minutes: dict[str, dict[int, int]],
) -> datetime | None:
    """Convert P75 local minutes → UTC datetime for the given date."""
    month = d.month
    minutes = p75_minutes.get(metric, {}).get(month)
    if minutes is None:
        return None
    local_midnight = datetime(d.year, d.month, d.day, 0, 0, tzinfo=tz)
    local_p75 = local_midnight + timedelta(minutes=minutes)
    return local_p75.astimezone(ZoneInfo("UTC"))


def analyze(records: list[dict]) -> None:
    n = len(records)
    print(f"\nTotal (metric, date) records: {n}")
    if n == 0:
        return

    def _pct(vals: list[float], pct: float) -> float:
        s = sorted(vals)
        idx = max(int(math.ceil(pct / 100 * len(s))) - 1, 0)
        return s[min(idx, len(s) - 1)]

    # ── Main split: running min warmer vs colder than GFS at P75 ──
    above = [r for r in records if r["overshoot"] > 0]
    on    = [r for r in records if r["overshoot"] == 0]
    below = [r for r in records if r["overshoot"] < 0]

    def show(group, label):
        if not group:
            print(f"  {label}: n=0")
            return
        cont  = [r["continued"] for r in group]
        avg_c = sum(cont) / len(cont)
        avg_o = sum(r["overshoot"] for r in group) / len(group)
        p50   = _pct(cont, 50)
        p75   = _pct(cont, 75)
        p90   = _pct(cont, 90)
        p_ge1 = sum(1 for c in cont if c >= 1) / len(cont)
        p_ge2 = sum(1 for c in cont if c >= 2) / len(cont)
        print(
            f"  {label}: n={len(group):>5}  avg_os={avg_o:+.1f}°  "
            f"avg={avg_c:+.2f}°  p50={p50:+.1f}°  p75={p75:+.1f}°  p90={p90:+.1f}°  "
            f"≥1°={p_ge1:.0%}  ≥2°={p_ge2:.0%}"
        )

    print("\n=== Overshoot at P75 vs continued cooling after P75 ===")
    print("  overshoot = running_min_at_p75 − gfs_daily_min  (positive = warmer than GFS)")
    print("  continued = running_min_at_p75 − actual_daily_low  (positive = more cooling after P75)")
    print("  All values continuous (no rounding).\n")
    show(above, "running_min > GFS (warmer)")
    show(on,    "running_min = GFS (exact) ")
    show(below, "running_min < GFS (colder)")

    # ── Overshoot magnitude buckets (continuous) ──
    print("\n=== Overshoot magnitude → continued cooling distribution ===")
    buckets: dict[str, list] = defaultdict(list)
    for r in records:
        o = r["overshoot"]
        if o <= -4:      k = "≤-4°"
        elif o < -3:     k = "(-4,-3)"
        elif o < -2:     k = "(-3,-2)"
        elif o < -1:     k = "(-2,-1)"
        elif o < 0:      k = "(-1, 0)"
        elif o == 0:     k = "  0°"
        elif o <= 1:     k = "(0, +1]"
        elif o <= 2:     k = "(+1,+2]"
        elif o <= 3:     k = "(+2,+3]"
        elif o <= 4:     k = "(+3,+4]"
        else:            k = "  >+4°"
        buckets[k].append(r)

    order = ["≤-4°", "(-4,-3)", "(-3,-2)", "(-2,-1)", "(-1, 0)", "  0°",
             "(0, +1]", "(+1,+2]", "(+2,+3]", "(+3,+4]", "  >+4°"]
    print(f"  {'overshoot':>10}  {'n':>5}  {'avg':>7}  {'p50':>6}  {'p75':>6}  {'p90':>6}  {'≥0.5°':>6}  {'≥1°':>5}  {'≥2°':>5}")
    for k in order:
        grp = buckets.get(k, [])
        if not grp:
            continue
        cont = [r["continued"] for r in grp]
        avg  = sum(cont) / len(cont)
        p50  = _pct(cont, 50)
        p75  = _pct(cont, 75)
        p90  = _pct(cont, 90)
        ph   = sum(1 for c in cont if c >= 0.5) / len(cont)
        p1   = sum(1 for c in cont if c >= 1.0) / len(cont)
        p2   = sum(1 for c in cont if c >= 2.0) / len(cont)
        print(f"  {k:>10}  {len(grp):>5}  {avg:>+6.2f}°  {p50:>+5.1f}°  {p75:>+5.1f}°  {p90:>+5.1f}°  {ph:>5.0%}  {p1:>4.0%}  {p2:>4.0%}")

    # ── By month: how much cooling remains at P75 time? ──
    print("\n=== By month: continued cooling at P75 time (all records) ===")
    month_records: dict[int, list] = defaultdict(list)
    for r in records:
        month_records[datetime.fromisoformat(r["date"]).month].append(r)
    print(f"  {'month':>5}  {'n':>5}  {'avg':>7}  {'p50':>6}  {'p75':>6}  {'p90':>6}  {'≥0.5°':>6}  {'≥1°':>5}")
    for month in sorted(month_records):
        grp = month_records[month]
        cont = [r["continued"] for r in grp]
        avg  = sum(cont) / len(cont)
        p50  = _pct(cont, 50)
        p75  = _pct(cont, 75)
        p90  = _pct(cont, 90)
        ph   = sum(1 for c in cont if c >= 0.5) / len(cont)
        p1   = sum(1 for c in cont if c >= 1.0) / len(cont)
        print(f"  {month:>5}  {len(grp):>5}  {avg:>+6.2f}°  {p50:>+5.1f}°  {p75:>+5.1f}°  {p90:>+5.1f}°  {ph:>5.0%}  {p1:>4.0%}")

    # ── Per-city summary ──
    print("\n=== Per-city: avg continued cooling when warmer vs colder than GFS ===")
    city_records: dict[str, list] = defaultdict(list)
    for r in records:
        city_records[r["metric"]].append(r)
    print(f"  {'metric':<20}  {'n_warm':>6}  {'avg_warm':>9}  {'≥1°_warm':>9}  {'n_cold':>6}  {'avg_cold':>9}  {'≥1°_cold':>9}")
    for metric in sorted(city_records):
        grp  = city_records[metric]
        warm = [r for r in grp if r["overshoot"] > 0]
        cold = [r for r in grp if r["overshoot"] < 0]
        avg_w = (sum(r["continued"] for r in warm) / len(warm)) if warm else float("nan")
        avg_c = (sum(r["continued"] for r in cold) / len(cold)) if cold else float("nan")
        p1_w  = (sum(1 for r in warm if r["continued"] >= 1) / len(warm)) if warm else float("nan")
        p1_c  = (sum(1 for r in cold if r["continued"] >= 1) / len(cold)) if cold else float("nan")
        print(
            f"  {metric:<20}  {len(warm):>6}  {avg_w:>+8.2f}°  {p1_w:>8.0%}  "
            f"{len(cold):>6}  {avg_c:>+8.2f}°  {p1_c:>8.0%}"
        )


# ── Main ───────────────────────────────────────────────────────────────────────

async def main(start: str, end: str) -> None:
    p75_minutes = load_p75_minutes()
    if not p75_minutes:
        print("No P75 data loaded. Aborting.", file=sys.stderr)
        sys.exit(1)

    print(f"Fetching data for {len(LOW_METRICS)} cities, {start} → {end}")
    print("(cached fetches skip download)\n")

    records: list[dict] = []

    async with aiohttp.ClientSession() as session:
        for metric, (city_name, lat, lon, tz) in LOW_METRICS.items():
            station, network = IEM_STATIONS[metric]
            short = metric.replace("temp_low_", "")
            print(f"  {short:<6} ({station}) ...", end="", flush=True)

            gfs_data = await fetch_gfs_daily_min(session, lat, lon, start, end, short)
            await asyncio.sleep(1.0)
            iem_data = await fetch_iem_hourly(session, station, network, start, end, short)
            await asyncio.sleep(1.5)

            n_added = 0
            start_d = date.fromisoformat(start)
            end_d   = date.fromisoformat(end)
            d = start_d
            while d <= end_d:
                ds = d.isoformat()
                gfs_fcst = gfs_data.get(ds)
                obs = iem_data.get(ds)
                if gfs_fcst is None or not obs:
                    d += timedelta(days=1)
                    continue

                p75_dt = p75_utc(metric, d, tz, p75_minutes)
                if p75_dt is None:
                    d += timedelta(days=1)
                    continue

                asos_p75 = running_min_at_time(obs, p75_dt)
                actual_lo = min(t for _, t in obs)

                if asos_p75 is None:
                    d += timedelta(days=1)
                    continue

                records.append({
                    "metric":    metric,
                    "date":      ds,
                    "gfs_fcst":  gfs_fcst,
                    "asos_p75":  asos_p75,
                    "actual_lo": actual_lo,
                    "overshoot": asos_p75 - gfs_fcst,    # positive = warmer than GFS
                    "continued": asos_p75 - actual_lo,   # positive = more cooling after P75
                })
                n_added += 1
                d += timedelta(days=1)

            print(f" {n_added} days")
            await asyncio.sleep(0.3)

    analyze(records)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Backtest GFS daily-min gate for KXLOWT NO signals."
    )
    parser.add_argument("--start", default="2022-05-01")
    parser.add_argument("--end",   default="2025-09-30")
    args = parser.parse_args()
    asyncio.run(main(args.start, args.end))
